package com.emprestimo.app.Script.options;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum EmpregadorSQL {

    SQL_GETEMPREGADOR ("SELECT * FROM EMPREGADORES ORDER BY 2 ASC"),

    SQL_GETIDEMPREGADOR ("SELECT * FROM EMPREGADORES WHERE idempregador = ?"),

    SQL_POSTEMPREGADOR("INSERT INTO EMPREGADORES (EMPREGADOR) VALUES (?)"),

    SQL_DELETE_EMPREGADOR("DELETE FROM EMPREGADORES WHERE IDEMPREGADOR = ?"),

    SQL_UPDATE_EMPREGADOR ("UPDATE EMPREGADORES SET EMPREGADOR = ? WHERE IDEMPREGADOR = ?"),

    SQL_INSERT_PESSOAEMPREGADOR("INSERT INTO (IDPESSOA,IDEMPREGADOR) VALUES (?,?)");

    public String value;

}
