package com.emprestimo.app.Scripty;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum PessoaSQL{
    /*
     Selects
     */
    SQL_GET_NOMEPESSOA ("SELECT * FROM PESSOA WHERE NOME = ?"),
    // COMO USAR O LIKE SQL_GET_NOMEPESSOA ("SELECT NOME FROM PESSOA WHERE NOME LIKE '?%'"),

    SQL_GET_CPFPESSOA ("SELECT * FROM PESSOA WHERE CPF = ?"),
    SQL_GET_NBENEFICIOPESSOAS ("SELECT * FROM PESSOA WHERE NUMBENEFICIO = ?"),
    SQL_GET_LIST_PESSOAS ("SELECT * FROM PESSOA"),
    /*
    Insert
     */
    SQL_INSERT_PESSOA("INSERT INTO PESSOA (NOME,CPF,RG,DATAEMISSAORG,UFRG,RENDA,DATANASCIMENTO,NATURALIDAE,ESTADONASCIMENTO,ESTADOCIVIL,NOMEPAI,NOMEMAE,EMAIL,INDICACAO,NUMBENEFICIO,MATRICULA) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
    /*
    Delete
     */
    SQL_DELETE_CPFPESSOA("DELETE FROM PESSOA WHERE CPF = ?"),
    SQL_DELETE_NUMBENEFICIOPESSOA("DELETE FROM PESSOA WHERE NUMBENEFICIO = ?"),

    /*
    Update
     */
    SQL_UPDATE_PESSOA("UPDATE PESSOA SET NOME = ?" +
            ",CPF = ?,RG = ?,DATAEMISSAORG = ?,UFRG = ?,RENDA = ?" +
            ",DATANASCIMENTO = ?,NATURALIDAE = ?,ESTADONASCIMENTO = ?,ESTADOCIVIL = ?" +
            ",NOMEPAI = ?,NOMEMAE = ?,EMAIL = ?,INDICACAO = ?,NUMBENEFICIO = ?,MATRICULA = ?" +
            " WHERE CPF = ?");

     private String value;
}
